# Generated by Django 3.2.16 on 2023-01-21 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='detail',
        ),
    ]
