# Generated by Django 3.2.16 on 2023-01-21 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_remove_category_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
    ]
