# Generated by Django 3.2.16 on 2023-01-21 04:18

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_auto_20230121_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Acuerdo de confidencialidad y privacidad de información', 'ACUERDO'), ('Contrato de Servicios de Tecnologias de Información (IT)', 'CONTRATO_1'), ('Contrato de Servicios de Consultoria en el departamento de gerencia', 'CONTRATO_CG')], max_length=200, null=True, verbose_name='Tipo de oferta')),
                ('Law_type', models.CharField(choices=[('Juridicamente ', 'JURIDICO'), ('Naturalmente ', 'NATURAL')], max_length=20, null=True, verbose_name='Law Type')),
                ('Cli_title', models.CharField(choices=[('Sr', 'Señor.'), ('Sra', 'Señora.'), ('Sta', 'Señorita.'), ('Ing', 'Ingeniero'), ('Arq', 'Arquitecto'), ('Lic', 'Licenciado'), ('Phd', 'Doctor')], max_length=20, null=True, verbose_name='Title Type')),
                ('Business_type', models.CharField(choices=[('compañia', 'compañia'), ('negocio', 'negocio')], max_length=20, null=True, verbose_name='Business Type')),
                ('Business_name', models.CharField(choices=[('AP', 'ADRIAN PETROLEUM SERVICES S.A'), ('CDB', 'CENTRO DE DISEÑO Y DECORACIÓN EL BOSQUE'), ('ASM', 'CONJUNTO ALCAZAR DE SALAMANCA'), ('CHS', 'CONJUNTO HABITACIONAL SIERRA I Y II'), ('CSM', 'CONJUNTO SAN MARTÍN'), ('CS', 'CONJUNTO SIRAH'), ('VC', 'CONJUNTO VALLE CARTAGO'), ('VMU', 'CONJUNTO VIA MARINA UNO'), ('PZT', 'EDIFICIO PIAZZA TOSCANA'), ('APZ', 'EDIFICIO ARISTO PLAZA'), ('AL', 'EDIFICIO ASIEL'), ('ASP', 'EDIFICIO ASPEN'), ('BTP', 'EDIFICIO BATAN PLAZA'), ('BZ', 'EDIFICIO BIZANCIO'), ('BD', 'EDIFICIO BLUE DIAMOND II'), ('BT', 'EDIFICIO BRISTOL TORRE II'), ('CC', 'EDIFICIO CAMPUS CENTRAL'), ('CB', 'EDIFICIO CORYBA'), ('PD', 'EDIFICIO EL PEDREGAL'), ('FS', 'EDIFICIO FOUR SEASONS I'), ('KN', 'EDIFICIO KORONI'), ('KS', 'EDIFICIO KOUROS'), ('LG', 'EDIFICIO LAFARGUE'), ('MN', 'EDIFICIO METROPOLITAN'), ('PD', 'EDIFICIO PLUS DOS CENTRO DE NEGOCIOS'), ('PS', 'EDIFICIO PUERTAS DEL SOL'), ('SL', 'EDIFICIO SCALA '), ('SG', 'EDIFICIO SOHO GALAXY'), ('SR', 'EDIFICIO SORELINA'), ('TB', 'EDIFICIO TENIS BOULEVARD'), ('TA', 'EDIFICIO TERRAZAS ATRIUM'), ('TC', 'EDIFICIO TORRE CARE'), ('TF', 'EDIFICIO TORRE FINLANDIA'), ('TS', 'EDIFICIO TORRE SOL I'), ('TR', 'EDIFICIO TRIER'), ('VR', 'EDIFICIO VERONES'), ('VN', 'EDIFICIO VIENA'), ('AQ', 'FIDEICOMISO INMOBILIARIO PARK QUITO'), ('HD', 'AGENCIA HOMEDETAIL'), ('KZ', 'EDIFICIO KENZE'), ('CP', 'LA CASA EN EL PARQUE'), ('NS', 'EDIFICIO NOVAK STATUS'), ('PN', 'EDIFICIO PRISMA NORTE'), ('CS', 'CRISTIAN SILVA DOMINGUEZ'), ('VN', 'EDIFICIO TORRE DEL SOL'), ('TN', 'EDIFICIO TORRE NOHA')], max_length=100, null=True, verbose_name='Nombre de edificio')),
                ('first_name', models.CharField(max_length=50, verbose_name='first names')),
                ('last_name', models.CharField(max_length=50, verbose_name='last names')),
                ('CI', models.BigIntegerField(max_length=13, null=True, verbose_name='Identy ID')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('address', models.CharField(max_length=250, verbose_name='address')),
                ('postal_code', models.CharField(max_length=20, verbose_name='postal code')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('country', models.CharField(max_length=100, null=True, verbose_name='country')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='comercial.oferta')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='comercial.service')),
            ],
        ),
        migrations.CreateModel(
            name='AcuerdoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clausura', models.CharField(max_length=250, null=True, verbose_name='clausura')),
                ('intro', ckeditor.fields.RichTextField(null=True)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Acuerdo_items', to='comercial.oferta')),
            ],
        ),
    ]
