# Generated by Django 3.2.16 on 2023-02-14 02:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20221220_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Business_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Business name'),
        ),
        migrations.AddField(
            model_name='order',
            name='CI',
            field=models.BigIntegerField(max_length=13, null=True, verbose_name='Identy ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='IVA',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='order',
            name='cloud_server',
            field=models.CharField(choices=[('AWS Cloud', 'AWS Cloud'), ('Digital Ocean', 'Digital Ocean'), ('Microsoft Azure', 'Microsoft Azure'), ('Google Cloud', 'Google Cloud'), ('SmartQuail Cloud', 'SmartQuail Cloud')], max_length=50, null=True, verbose_name='Cloud Servers'),
        ),
        migrations.AddField(
            model_name='order',
            name='deployd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='ip_address_cloud',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='project_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Project_name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=250, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=100, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(max_length=20, verbose_name='postal code'),
        ),
    ]
