# Generated by Django 3.2.13 on 2022-08-12 16:14

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_v10', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charms',
            name='banner_title13',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-10  '),
        ),
        migrations.AddField(
            model_name='charms',
            name='banner_title14',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-11 '),
        ),
        migrations.AddField(
            model_name='charms',
            name='banner_title15',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-12  '),
        ),
        migrations.AlterField(
            model_name='charms',
            name='banner_title10',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-7  '),
        ),
        migrations.AlterField(
            model_name='charms',
            name='banner_title11',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-8  '),
        ),
        migrations.AlterField(
            model_name='charms',
            name='banner_title12',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-9  '),
        ),
        migrations.AlterField(
            model_name='charms',
            name='banner_title8',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-5  '),
        ),
        migrations.AlterField(
            model_name='charms',
            name='banner_title9',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-6  '),
        ),
    ]
