# Generated by Django 3.2.13 on 2022-08-12 17:06

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_v10', '0002_auto_20220812_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='charms',
            name='banner_detail10',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='detalle de galeria-7 '),
        ),
        migrations.AddField(
            model_name='charms',
            name='banner_detail11',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='detalle de galeria-8 '),
        ),
        migrations.AddField(
            model_name='charms',
            name='banner_detail12',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='detalle de galeria-9 '),
        ),
        migrations.AddField(
            model_name='charms',
            name='banner_detail13',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='detalle de galeria-10 '),
        ),
        migrations.AddField(
            model_name='charms',
            name='banner_detail14',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='detalle de galeria-11 '),
        ),
        migrations.AddField(
            model_name='charms',
            name='banner_detail15',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='detalle de galeria-12 '),
        ),
        migrations.AddField(
            model_name='charms',
            name='banner_detail4',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='detalle de galeria-1 '),
        ),
        migrations.AddField(
            model_name='charms',
            name='banner_detail5',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='detalle de galeria-2 '),
        ),
        migrations.AddField(
            model_name='charms',
            name='banner_detail6',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='detalle de galeria-3 '),
        ),
        migrations.AddField(
            model_name='charms',
            name='banner_detail7',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='detalle de galeria-4 '),
        ),
        migrations.AddField(
            model_name='charms',
            name='banner_detail8',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='detalle de galeria-5 '),
        ),
        migrations.AddField(
            model_name='charms',
            name='banner_detail9',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='detalle de galeria-6 '),
        ),
    ]
