# Generated by Django 3.2.13 on 2022-08-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_v10', '0003_auto_20220812_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charms',
            name='banner_detail4',
            field=models.CharField(blank=True, max_length=100, verbose_name='detalle de galeria-1 '),
        ),
    ]
