# Generated by Django 3.2.13 on 2022-08-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_v10', '0004_alter_charms_banner_detail4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charms',
            name='banner_detail10',
            field=models.CharField(blank=True, max_length=1000, verbose_name='detalle de galeria-7 '),
        ),
        migrations.AlterField(
            model_name='charms',
            name='banner_detail11',
            field=models.CharField(blank=True, max_length=1000, verbose_name='detalle de galeria-8'),
        ),
        migrations.AlterField(
            model_name='charms',
            name='banner_detail12',
            field=models.CharField(blank=True, max_length=1000, verbose_name='detalle de galeria-9 '),
        ),
        migrations.AlterField(
            model_name='charms',
            name='banner_detail13',
            field=models.CharField(blank=True, max_length=1000, verbose_name='detalle de galeria-10'),
        ),
        migrations.AlterField(
            model_name='charms',
            name='banner_detail14',
            field=models.CharField(blank=True, max_length=1000, verbose_name='detalle de galeria-11 '),
        ),
        migrations.AlterField(
            model_name='charms',
            name='banner_detail15',
            field=models.CharField(blank=True, max_length=1000, verbose_name='detalle de galeria-12'),
        ),
        migrations.AlterField(
            model_name='charms',
            name='banner_detail4',
            field=models.CharField(blank=True, max_length=1000, verbose_name='detalle de galeria-1 '),
        ),
        migrations.AlterField(
            model_name='charms',
            name='banner_detail5',
            field=models.CharField(blank=True, max_length=1000, verbose_name='detalle de galeria-2 '),
        ),
        migrations.AlterField(
            model_name='charms',
            name='banner_detail6',
            field=models.CharField(blank=True, max_length=1000, verbose_name='detalle de galeria-3 '),
        ),
        migrations.AlterField(
            model_name='charms',
            name='banner_detail7',
            field=models.CharField(blank=True, max_length=1000, verbose_name='detalle de galeria-4 '),
        ),
        migrations.AlterField(
            model_name='charms',
            name='banner_detail8',
            field=models.CharField(blank=True, max_length=1000, verbose_name='detalle de galeria-5 '),
        ),
        migrations.AlterField(
            model_name='charms',
            name='banner_detail9',
            field=models.CharField(blank=True, max_length=1000, verbose_name='detalle de galeria-6 '),
        ),
    ]
