# Generated by Django 3.2.13 on 2022-08-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_v10', '0005_auto_20220812_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='environs',
            name='next',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Next'),
        ),
        migrations.AddField(
            model_name='environs',
            name='prev',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Prev'),
        ),
    ]
