# Generated by Django 3.2.13 on 2022-08-21 04:33

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_v10', '0008_auto_20220820_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='banner_title4',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Descripcion de la localizacion'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='banner_title5',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Email  '),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='banner_title6',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Adress  '),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='banner_title7',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='environs',
            name='banner_title7',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Next  '),
        ),
        migrations.AlterField(
            model_name='environs',
            name='banner_title8',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Prev '),
        ),
    ]
