# Generated by Django 3.2.13 on 2022-09-09 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('webapp_v10', '0011_consultas_9'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriadeimagenes_7',
            name='image_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo 5'),
        ),
        migrations.AlterField(
            model_name='galeriadeimagenes_7',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo 1'),
        ),
        migrations.AlterField(
            model_name='galeriadeimagenes_7',
            name='image_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo 2'),
        ),
        migrations.AlterField(
            model_name='galeriadeimagenes_7',
            name='image_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo 3'),
        ),
        migrations.AlterField(
            model_name='galeriadeimagenes_7',
            name='image_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo 4'),
        ),
        migrations.AlterField(
            model_name='galeriadeimagenes_7',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logotipo de Isla Floreana'),
        ),
    ]
