# Generated by Django 3.2.13 on 2022-09-09 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('webapp_v10', '0012_auto_20220908_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeriadeimagenes_5',
            name='image',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes_5',
            name='logo_3',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes_7',
            name='image_5',
        ),
        migrations.AlterField(
            model_name='galeriadeimagenes_5',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logotipo de Isla Floreana'),
        ),
        migrations.AlterField(
            model_name='galeriadeimagenes_5',
            name='logo_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo 0'),
        ),
        migrations.AlterField(
            model_name='galeriadeimagenes_7',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 1'),
        ),
        migrations.AlterField(
            model_name='galeriadeimagenes_7',
            name='image_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 2'),
        ),
        migrations.AlterField(
            model_name='galeriadeimagenes_7',
            name='image_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 3'),
        ),
        migrations.AlterField(
            model_name='galeriadeimagenes_7',
            name='image_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Advertising Thumb-Galeria'),
        ),
        migrations.AlterField(
            model_name='galeriadeimagenes_7',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logotipo de Juan Silva Photo'),
        ),
    ]
