# Generated by Django 3.2.13 on 2022-09-09 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_v10', '0014_auto_20220908_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeriadeimagenes_5',
            name='logo',
        ),
    ]
