# Generated by Django 3.2.16 on 2022-11-22 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('webapp_v10', '0017_auto_20220911_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriadeimagenes_5',
            name='logo_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo 5'),
        ),
    ]
