# Generated by Django 3.2.16 on 2023-02-05 01:42

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_v10', '0021_auto_20230205_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas_under',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='webapp_v10.under_contruction'),
        ),
    ]
