# Generated by Django 3.2.16 on 2023-01-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_alter_contract_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='type',
            field=models.CharField(choices=[('Acuerdo de alianza estratégica', 'ALIANZA'), ('Acuerdo de confidencialidad y privacidad de información', 'ACUERDO'), ('Contrato de Servicios de Tecnologias de Información (IT)', 'CONTRATO_1'), ('Contrato de Servicios de Consultoria en el departamento de gerencia', 'CONTRATO_CG')], max_length=200, null=True, verbose_name='Contract Type'),
        ),
    ]
