version: '3.9'

services:
  qnd12_app_stg:
    image: smartquail/qnd12_app_stg:latest
    restart: unless-stopped
    environment:
      - PORT=9000
    env_file:
      - .env_pro
    depends_on:
      - smartquaildb
    expose:
      - 9000
    ports:
      - "9000:9000"
    volumes:
      - static-data-qnd12:/qnd12_app_stg/qnd12_app_stg/qnd12_app_stg/staticfiles
      - static-data-qnd12:/qnd12_app_stg/qnd12_app_stg/qnd12_app_stg/media
      - static-data-qnd12:/qnd12_app_stg/qnd12_app_stg/qnd12_app_stg/static
    networks: 
      - lansmartquail
   # command: sh -c "chmod +x /scripts/migrations.sh && sh /scripts/migrations.sh && sh /scripts/run.sh"

  nginx:
    image: smartquail/qnd12_nginx:prod
    restart: always
    depends_on:
     - qnd12_app_stg
    ports:
    - 80:80
    - 443:443
    volumes:
    - certbot-web_2:/vol/www
    - proxy-dhparams_2:/vol/proxy
    - certbot-certs_2:/etc/letsencrypt
    env_file:
    - .env_pro
    networks:
    - lansmartquail

  smartquaildb:
    image: postgres:13-alpine
    restart: always
    command: -p 5432
    env_file:
      - .env_pro
    ports:
      - "5432:5432"
    expose:
     - 5432
    volumes:
      - smartquaildb_data:/var/lib/postgresql/data/
    networks: 
      - lansmartquail

  redis:
    image: redis:3.0
    restart: always
    expose:
      - 6388
    ports:
      - "6388:6388"
    volumes:
      - redis_data:/data
    entrypoint: redis-server --appendonly yes --port 6380
    networks: 
      - lansmartquail

volumes:
  smartquaildb_data:
  redis_data:
  static-data-qnd12:
  certbot-web_2:
  proxy-dhparams_2:
  certbot-certs_2:

networks: 
   lansmartquail:
       driver: bridge